on:
  push:
    branches:
      - main

jobs:
  compute_typescript_ratio_job:
    runs-on: ubuntu-latest
    name: A job to compute the ratio of Typescript to JavaScript lines of code
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compute Typescript - JavaScript LOC ratio
        uses: ./ # Uses an action in the root directory
        id: typescript-loc-ratio
        with:
          source-path: './example'
          datadog-metric: 'dev.gonfalon.typescript.progress'
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}